name: Greetings

on:
  pull_request_target:
  issues:
  workflow_dispatch:

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"


  system-info:
    runs-on: ubuntu-latest
    steps:
    - name: Print system information
      run: uname -a
    
    - name: Print hardware information
      run: lscpu
    
    - name: Print memory information
      run: free -h
    
    - name: Print disk information
      run: df -h
